---
url: 'https://reflux.link'
baseurl: /7777777star
language: ko
timezone: Asia/Seoul
title: 에듀킹
description: 에듀킹
incremental: false
destination: docs
paginate: 20
paginate_path: '/page/:num/'
collections:
  posts:
    output: true
    permalink: '/:title'
  stories:
    output: true
    permalink: '/stories/:title'
defaults:
  - scope:
      path: ''
      type: posts
    values:
      layout: post
  - scope:
      path: ''
      type: stories
    values:
      layout: amp-story
plugins:
  - jekyll-coffeescript
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-paginate
  - jekyll-relative-links
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-default-layout
  - jekyll-titles-from-headings
  - jekyll-redirect-from
  - jekyll-avatar
  - jemoji
  - jekyll-mentions
  - jekyll-include-cache
include:
  - _reflux
  - _amp
  - .htaccess
exclude:
  - docs
  - CNAME
  - LICENSE
  - README.md
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
id: '54370843'
blogNo: '54370843'
blogId: 7777777star
blogName: 에듀킹
blogOwner: false
displayNickName: 에듀킹(7777777star)
bothNeighbor: false
neighbor: false
nickName: 에듀킹
officialBlog: false
powerBlog: false
mobileTitleImage:
  originalImage: 'https://blogimgs.pstatic.net/mobile/mobile_title08_l.jpg'
  croppedImage: 'https://blogimgs.pstatic.net/mobile/mobile_title08_l.jpg'
  previewImage: 'https://blogimgs.pstatic.net/mobile/mobile_title08_l.jpg'
dayVisitorCount: 1
subscriberCount: 35
totalVisitorCount: 1572
block: false
mylogBlock: false
profileImagePath: ''
encodedProfileImagePath: ''
guest: true
suggestionBlog: false
initializingBlog: false
relationType: 4
showReservationGuide: false
deletedAt: null
createdAt: 2019-03-17T12:15:29.146Z
updatedAt: 2019-05-30T00:39:03.081Z
---

