---
title: 킹에듀
description: 킹에듀
url: 'https://reflux.link'
baseUrl: /7777777star
language: ko
timezone: Asia/Seoul
permalink: '/:title'
paginate: 20
paginate_path: '/page/:num/'
ampdir: ''
markdown: CommonMark
commonmark:
  options:
    - SMART
    - FOOTNOTES
  extensions:
    - strikethrough
    - autolink
    - table
minify_html: false
incremental: true
plugins:
  - jekyll-paginate
  - jekyll-commonmark
  - jekyll-include-cache
gem:
  - amp-jekyll
exclude:
  - .jekyll-cache
  - README.md
  - LICENSE
  - CNAME
  - Gemfile
  - Gemfile.lock
  - _includes/styles.min.css
keep_files:
  - assets
id: '54370843'
blogNo: '54370843'
blogId: 7777777star
blogName: 킹에듀
blogOwner: false
displayNickName: 에듀킹(7777777star)
bothNeighbor: false
neighbor: false
nickName: 에듀킹
officialBlog: false
powerBlog: false
mobileTitleImage:
  originalImage: 'https://blogimgs.pstatic.net/mobile/mobile_title08_l.jpg'
  croppedImage: 'https://blogimgs.pstatic.net/mobile/mobile_title08_l.jpg'
  previewImage: 'https://blogimgs.pstatic.net/mobile/mobile_title08_l.jpg'
dayVisitorCount: 7
subscriberCount: 9
totalVisitorCount: 565
block: false
mylogBlock: false
profileImagePath: ''
encodedProfileImagePath: ''
guest: true
suggestionBlog: false
initializingBlog: false
relationType: 4
showReservationGuide: false
deletedAt: null
createdAt: 2019-03-17T12:15:29.146Z
updatedAt: 2019-03-19T21:49:45.783Z
---

